CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE "users" (
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "email" text NOT NULL UNIQUE,
    "full_name" text NOT NULL,
    "has_completed_onboarding" boolean DEFAULT false,
    "height" double precision,
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "is_discoverable" boolean NOT NULL DEFAULT false,
    "language" text NOT NULL,
    "target_weight" double precision,
    "food_preferences_positive" text,
    "food_preferences_negative" text
);

CREATE TABLE "meals" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "meal" text NOT NULL,
    "section_key" text NOT NULL,
    "day" timestamptz NOT NULL,
    "user_id" bigint NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
    "note" text,
    "rating" double precision
);

CREATE TABLE "measurements" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "date" date NOT NULL,
    "weight" double precision NOT NULL,
    "fat_percentage" double precision,
    "user_id" bigint NOT NULL REFERENCES "users"("id") ON DELETE CASCADE
);

CREATE TABLE "activities" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "date" date NOT NULL,
    "activity" text NOT NULL,
    "user_id" bigint NOT NULL REFERENCES "users"("id") ON DELETE CASCADE
);

CREATE TABLE "meals_pool" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "content" text NOT NULL,
    "user_id" bigint NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
    CONSTRAINT "meals_pool_user_id_content_unique" UNIQUE ("user_id", "content")
);

CREATE TABLE "connections" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "user_id" bigint NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
    "connection_user_id" bigint NOT NULL REFERENCES "users"("id") ON DELETE CASCADE
);

CREATE TABLE "notifications" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "date" date NOT NULL,
    "notification_type" text NOT NULL,
    "request_user_id" bigint NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
    "target_user_id" bigint NOT NULL REFERENCES "users"("id") ON DELETE CASCADE
);
