create table
  public.users (
    created_at timestamp with time zone not null default now(),
    email text not null,
    full_name text not null,
    is_nutritionist boolean not null default false,
    height double precision null,
    language text not null,
    id bigint generated by default as identity,
    constraint users_pkey primary key (email),
    constraint users_email_key unique (email),
    constraint users_id_key unique (id)
  ) tablespace pg_default;
